### PR TITLE
Issue/157 vid reveal

### LINKED ISSUE #157: Video Reveal
Video Reveal is a block type within Web Express that initial presents more like a hero, but clicking it swaps to and plays a YouTube video.  

The block allows editors to upload an image, add some text for the hero display.

Demo: https://www.colorado.edu/demos/web-express/add-bundles/video-reveal-block

### PR DESCRIPTION
**Pull request by jcsparks**
Closes #157 

Changes to custom pages and custom paragraphs as well.

### CODE REVIEW

**Comment by jnicholCU** [comment]
Everything seems to be working well. 
On the webexpress version they have the ability to close the video and load the place holder image again. 
Do we want that functionality as well?
I also want to try and figure out how to remove the media library edit button because I think it'll cause more problems than not.

**Comment by jacob-korf** [comment]
After testing, it seems to function well and looks nice. Once the changes Josh brought up, I think it should be good to go.

**Comment by jcsparks** [comment]
> Everything seems to be working well. On the webexpress version they have the ability to close the video and load the place holder image again. Do we want that functionality as well? I also want to try and figure out how to remove the media library edit button because I think it'll cause more problems than not.

Updated, can you retest.  Known issue with switching back to image while video is playing.

**Comment by jnicholCU** [comment]
Tested the reveal again. Looks like it's working fine with the expected issue already mentioned

**Review by jacob-korf — APPROVED** [review]
Works on my end well, merging and closing

**Pull request merged**
