### PR TITLE
Issue76

### PR DESCRIPTION
**Pull request by jacob-korf**
Social Media Icon Block fully implemented. It currently runs in Above Body Content, Above Content, Below Content, and Below Body Content

### CODE REVIEW

**Comment by jnicholCU** [comment]
Everything seems to be working well for me. I think this might be something we want to add to the sidebars as an option as well. What do you think @jcsparks ?

**Review by jcsparks — CHANGES_REQUESTED** [review]
The functionality is spot-on for this issue, works as requested.  However, I think the styling should use the existing Express model as a baseline for how this should look.  The Icons should have square colored backgrounds in the prominent color of the social media brand and therefore all be the same size.  

Also the vertical alignment should have a text descriptor along with the icon as the icons by themselves can seem a little bare in that orientation.  

See : https://www.colorado.edu/demos/web-express/add-bundles/social-links-block

**Review by jcsparks — CHANGES_REQUESTED** [review]
Great, this is all looking good.  

Looks like we have icon interpolation for the bigger social media companies working.  
We should add in : 
- Flickr
- Google Plus
- Reddit
- Vimeo
- WordPress
- TikTok
- Others?

**Review by jcsparks — APPROVED** [review]
Looks good to me.  Will be easy to extend and add other social media sites as needed.  Good work @jacob-korf.

**Pull request merged**
